export const NEWS_SORT_BY_TITLE_REQUEST = 'NEWS_SORT_BY_TITLE_REQUEST';
export const NEWS_SORT_BY_TITLE_SUCCESS = 'NEWS_SORT_BY_TITLE_SUCCESS';
export const NEWS_SORT_BY_TITLE_FAIL = 'NEWS_SORT_BY_TITLE_FAIL';
export const NEWS_SORT_BY_TITLE_RESET = 'NEWS_SORT_BY_TITLE_RESET';

export const NEWS_SORT_BY_DATE_NEW_REQUEST = 'NEWS_SORT_BY_DATE_NEW_REQUEST';
export const NEWS_SORT_BY_DATE_NEW_SUCCESS = 'NEWS_SORT_BY_DATE_NEW_SUCCESS';
export const NEWS_SORT_BY_DATE_NEW_FAIL = 'NEWS_SORT_BY_DATE_NEW_FAIL';
export const NEWS_SORT_BY_DATE_NEW_RESET = 'NEWS_SORT_BY_DATE_NEW_RESET';

export const NEWS_SORT_BY_DATE_OLD_REQUEST = 'NEWS_SORT_BY_DATE_OLD_REQUEST';
export const NEWS_SORT_BY_DATE_OLD_SUCCESS = 'NEWS_SORT_BY_DATE_OLD_SUCCESS';
export const NEWS_SORT_BY_DATE_OLD_FAIL = 'NEWS_SORT_BY_DATE_OLD_FAIL';
export const NEWS_SORT_BY_DATE_OLD_RESET = 'NEWS_SORT_BY_DATE_OLD_RESET';

